### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by emptyarray** [colinta/motion-wiretap#9]
I occasionally this error, but I'm having trouble debugging it, because it doesn't occur every time.

```
wiretap.rb:92:in `trigger_changed_on:': wrong number of arguments (1 for 0) (ArgumentError)
    from wiretap.rb:83:in `block in trigger_changed:'
    from wiretap.rb:82:in `trigger_changed:'
    from wiretap.rb:95:in `block in trigger_changed_on:'
    from wiretap.rb:58:in `enqueue'
    from wiretap.rb:94:in `trigger_changed_on:'
    from wiretap.rb:83:in `block in trigger_changed:'
    from wiretap.rb:82:in `trigger_changed:'
    from wiretap.rb:261:in `observeValueForKeyPath:ofObject:change:context:'
```

Here is the (obfuscated) code that causes the error, after I changed a dog's hunger.

``` ruby
# feed the hungriest dog whenever that dog changes
    @dogs_wiretap = @dogs.map do |dog|
      dog.wiretap(:hunger)
    end.wiretap.reduce do
      Dog.all.hungriest
    end.listen do |hungriest_dog|
      hungriest_dog.feed
    end
```

It's hard to tell if the problem is in motion-wiretap, or somewhere in my code. If the error occurred consistently, then I would suspect my code more. I've seen this same exception occur inconsistently elsewhere, which was why I'm wondering if motion-wiretap is involved. 

Any help debugging this would be much appreciated.

**Comment by colinta** [comment]
I _think_ this is a motion-wiretap thing.  I've seen a similar bug, but also cannot reproduce it.

**Comment by colinta** [comment]
Or it's some obscure rubymotion issue w/ blocks.

**Comment by emptyarray** [comment]
Glad it's not just me. I've seen it in two situations: this one, and another one. I think the common factor is that they both involved WiretapArrays. Was that the case for you, also?

**Comment by colinta** [comment]
Hmm, yes I think it DID!  And actually, I removed that array and I haven't seen it in a long time...

interesting...

**Comment by colinta** [comment]
I was seeing this again recently, and it turns out it was a method buried deep inside the triggered block.  It really WAS a `wrong number of arguments` error, but the stack trace was showing the motion-wiretap block, not the actual place in code!  I wonder if you're in a similar situation.

I discovered this by using `rake debug=1` and the stack trace showed it immediately.

**Comment by colinta** [comment]
Ah interesting!  Great clue, thanks!

**Comment by nathankot** [comment]
Hey sorry, I deleted my last post because somewhere along the line I got confused and the fix wasn't working :( I've written some failing tests and gonna give it a good crack over the week

## 

Nathan Kot
